### ISSUE TITLE
Android app in a demoable state

### ISSUE THREAD

**Issue by lloyd** [mozilla/openwebapps#13]
It'd be useful to demo some of the features and interactions of the openwebapps android app for the integration release.  It should be in a demoable state (and perhaps an `.apk` should be available for installation for those on the bleeding edge).

**Comment by lloyd** [comment]
All I need here is about 8 seconds of screen-cast to go along with the audio track, so it doesn't need to be demo-able by anyone else

**Comment by lloyd** [comment]
anant passed me an 8s video clip!  this is done.

**Comment by anantn** [comment]
Adding a note for future reference, the APK file for the application is at: http://people.mozilla.com/~anarayanan/Soup.apk

In order to make it usable by the general public, we need to start publishing app manifests to the sync server via: a) HTML dashboard, b) Firefox Extension and c) Chrome Extension (?). Further changes to the Android client itself are likely to be unnecessary.
