### ISSUE TITLE
navigating app tab away to other URL does not reset tab's appiness state

### ISSUE THREAD

**Issue by benadida** [mozilla/openwebapps#31]
e.g. launch app, navigate app tab somewhere else, open up dashboard of apps, click the same app, brings app tab back but remains at new non-appy URL.

**Comment by anantn** [comment]
Thought about this a bit -- a simple implementation would be to attach a listener for the DOMContentLoaded event and reset the tab state as not being an app anymore. While testing this, I noticed it will not work in the case of a browser restart, because the event handler will not be registered again.

I think it touches upon the larger issue of what we should consider to be an 'app tab'. I think we should simply prevent the user from navigating away from that application's origin domain. This is also much safer for the user.

For an initial stab at implementation, we might simply hide the URL bar, and then catch the more complicated cases such as link-clicks via a handler for the app tab's nsIWebProgressListener.

**Comment by benadida** [comment]
I agree with your reasoning and conclusion. Let's do it!

**Comment by anantn** [comment]
First part of this is in: https://github.com/mozilla/openwebapps/commit/a005e4d44d69f62341d2977a5b9265fa7552bd59

Now we'll have to make sure that any clicks inside the content of the app tab that are outside that the app domain open in a new tab.
