### ISSUE TITLE
Host minified JS APIs on site

### ISSUE THREAD

**Issue by michaelrhanson** [mozilla/openwebapps#84]
We should serve minified JS APIs from the site.

**Comment by ianb** [comment]
site/tools/compress_html.py has a tool specifically for building include.html (it inlines what resources it can, and compresses what it can).  It uses the YUI Compressor; I have no particular opinion on compressors, but I think other people at Mozilla use YUI.  We should have a build script for the site.

We should also test the minified JS.

**Comment by matthewp** [comment]
We also need to have a version number on the file so that the endpoint can be used.  Otherwise I'd want to always serve it from my local to ensure a stable version.

**Comment by ianb** [comment]
mattewp: can you expand?  I expect /jsapi/include.js to be unversioned and the public documented way to access the API.  For caching purposes other resources might get version numbers.  These URL-addressable APIs however only apply to one implementation of openwebapps (the pure-HTML implementation), so no site can ensure that a particular version of the API is used.  You can serve include.js locally, but other files cannot be served locally without creating a distinct application repository.

**Comment by matthewp** [comment]
Maybe I'm misunderstanding how this works. I've never heard of a js library that isn't actively developed.  Since this is a big library and downloads slowly on mobile, I'm hoping to use the mozilla.org endpoint so that some users will already have it cached. I'm not sure I'm comfortable with that if it's not minified, gzipped, and versioned.

**Comment by ianb** [comment]
mattewp: yes, this is a bit different from a normal Javascript library; it's really more of a service than a library.  There are multiple providers of the service, and applications can't select the provider – they have to make do with whatever provider the user shows up with.  One "provider" is the HTML and Javascript implementation, for people without native browser support.  But even this provider is actually bound to the user, not the application; there is a library that the application must load to actually use these APIs (since without browser support we cannot inject the APIs): `/jsapi/include.js` – however, this file is really just for communicating with other Javascript that Mozilla hosts, and that has to be hosted at a specific domain because the domain is essentially where the users list of applications are "stored".

**Comment by ianb** [comment]
implemented
